=begin
#Data Plane

#https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/inference_error_response'
require 'openapi_client/models/inference_request'
require 'openapi_client/models/inference_response'
require 'openapi_client/models/metadata_model_error_response'
require 'openapi_client/models/metadata_model_response'
require 'openapi_client/models/metadata_server_error_response'
require 'openapi_client/models/metadata_server_response'
require 'openapi_client/models/metadata_tensor'
require 'openapi_client/models/request_input'
require 'openapi_client/models/request_output'
require 'openapi_client/models/response_output'

# APIs
require 'openapi_client/api/default_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
