=begin
#Data Plane

#https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.2.1

=end

module TritonInferenceClient
  VERSION = '1.0.0'
end
